export const RESET_SERVER_MESSAGES = "RESET_SERVER_MESSAGES";
export const SERVER_ERROR = "SERVER_ERROR";
export const SERVER_MESSAGE = "SERVER_MESSAGE";

export const USERS_CREATE = "USERS/CREATE";
export const USERS_DELETE = "USERS/DELETE";
export const USERS_FETCH = "USERS/FETCH";
export const USERS_SEED = "USERS/SEED";
export const USERS_SET_DATA = "USERS/SET_DATA";
export const USERS_UPDATE = "USERS/UPDATE";
