export default props => [
	{
		name: "userName",
		type: "text",
		label: "Username",
		value: props.userName || "",
		errors: "",
		style: { width: "46%", display: "inline-block", marginRight: 10 },
		required: true,
	},
	{
		name: "email",
		type: "text",
		label: "Email",
		value: props.email || "",
		errors: "",
		style: { width: "46%", display: "inline-block" },
		required: true,
	},
	{
		name: "firstName",
		type: "text",
		label: "First Name",
		value: props.firstName || "",
		errors: "",
		style: { width: "46%", display: "inline-block", marginRight: 10 },
		required: true,
	},
	{
		name: "lastName",
		type: "text",
		label: "Last Name",
		value: props.lastName || "",
		errors: "",
		style: { width: "46%", display: "inline-block" },
		required: true,
	},
	{
		name: "street",
		type: "text",
		label: "Street",
		value: props.address ? props.address.street : "",
		errors: "",
		style: { width: "65%", display: "inline-block", marginRight: 10 },
		required: true,
	},
	{
		name: "suite",
		type: "text",
		label: "Suite",
		value: props.address ? props.address.suite : "",
		errors: "",
		style: { width: "27%", display: "inline-block" },
	},
	{
		name: "city",
		type: "text",
		label: "City",
		value: props.address ? props.address.city : "",
		errors: "",
		style: { width: "35%", display: "inline-block", marginRight: 10 },
		required: true,
	},
	{
		name: "state",
		type: "text",
		label: "State",
		value: props.address ? props.address.state : "",
		errors: "",
		style: { width: "35%", display: "inline-block", marginRight: 10 },
		required: true,
	},
	{
		name: "zipCode",
		type: "text",
		label: "Zip Code",
		value: props.address ? props.address.zipCode : "",
		errors: "",
		style: { width: "18%", display: "inline-block" },
		required: true,
	},
	{
		name: "backgroundInfo",
		type: "textarea",
		label: "Background Infomation",
		value: props.backgroundInfo || "",
		errors: "",
		required: true,
	},
];
