import { BaseFieldProps, UserFormProps } from "~types";

const fields = (props: UserFormProps): BaseFieldProps[] => [
  {
    name: "userName",
    type: "text",
    label: "Username",
    value: props.userName || "",
    errors: "",
    style: { width: "50%" },
    required: true,
  },
  {
    name: "email",
    type: "text",
    label: "Email",
    value: props.email || "",
    errors: "",
    style: { width: "50%" },
    required: true,
  },
  {
    name: "firstName",
    type: "text",
    label: "First Name",
    value: props.firstName || "",
    errors: "",
    style: { width: "50%" },
    required: true,
  },
  {
    name: "lastName",
    type: "text",
    label: "Last Name",
    value: props.lastName || "",
    errors: "",
    style: { width: "50%" },
    required: true,
  },
  {
    name: "street",
    type: "text",
    label: "Street",
    value: props.address ? props.address.street : "",
    errors: "",
    style: { width: "75%" },
    required: true,
  },
  {
    name: "suite",
    type: "text",
    label: "Suite",
    value: props.address ? props.address.suite : "",
    errors: "",
    style: { width: "25%" },
    required: false,
  },
  {
    name: "city",
    type: "text",
    label: "City",
    value: props.address ? props.address.city : "",
    errors: "",
    style: { width: "40%" },
    required: true,
  },
  {
    name: "state",
    type: "text",
    label: "State",
    value: props.address ? props.address.state : "",
    errors: "",
    style: { width: "40%" },
    required: true,
  },
  {
    name: "zipCode",
    type: "text",
    label: "Zip Code",
    value: props.address ? props.address.zipCode : "",
    errors: "",
    style: { width: "20%" },
    required: true,
  },
  {
    name: "backgroundInfo",
    type: "textarea",
    label: "Background Infomation",
    value: props.backgroundInfo || "",
    errors: "",
    style: { width: "100%" },
    required: true,
  },
];

export default fields;
